version: '3'
services:

  mariadb:
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    build: requirements/mariadb
    volumes:
      - mariadb:var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: requirements/nginx
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/nfs/homes/eberger/Desktop/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/nfs/homes/eberger/Desktop/data/mariadb'

networks:
  inception:
    driver: bridge
